---
- name: put cruise-config in the correct place
  template: src=cruise-config.xml dest=/etc/go/cruise-config.xml owner=go group=go mode=0644
  notify:
    - restart go-server

- name: install build-essential
  apt: name=build-essential state=present

- name: install native db libraries
  apt: name=libpq-dev state=present
  apt: name=libsqlite3-dev state=present

- name: setup go .bashrc
  copy: src=.bashrc dest=/var/go/.bashrc owner=go group=go mode=0644
